import Head from "next/head";

import Navbar from "components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Textto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <div className="h-screen flex justify-center items-center bg-[url('/moving-bg.svg')] bg-no-repeat bg-cover">
        <div>
          <h1 className="text-gray-800 dark:text-white LargeTextSize">
            best chatapp
          </h1>
          <h1 className="text-gray-600 dark:text-gray-400 LargeTextSize">
            ever.
          </h1>
        </div>
      </div>
    </>
  );
}
